"""initial

Revision ID: 001
Revises: 
Create Date: 2024-09-21 22:24:53.204582

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '001'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('twitter_posts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tweet_id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('preview_content', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk__twitter_posts')),
    sa.UniqueConstraint('tweet_id', name='uq_tweet_id'),
    sa.UniqueConstraint('tweet_id', name=op.f('uq__twitter_posts__tweet_id'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('twitter_posts')
    # ### end Alembic commands ###
