"""update miner

Revision ID: 002
Revises: 001
Create Date: 2024-09-22 13:18:45.550239

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '002'
down_revision: Union[str, None] = '001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('twitter_posts', sa.Column('user_id', sa.String(), nullable=False))
    op.create_unique_constraint(op.f('uq__twitter_posts__tweet_id'), 'twitter_posts', ['tweet_id'])
    op.drop_column('twitter_posts', 'preview_content')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('twitter_posts', sa.Column('preview_content', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(op.f('uq__twitter_posts__tweet_id'), 'twitter_posts', type_='unique')
    op.drop_column('twitter_posts', 'user_id')
    # ### end Alembic commands ###
