"""initial

Revision ID: 001
Revises: 
Create Date: 2024-09-21 22:50:43.907974

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '001'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('api_keys',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk__api_keys')),
    sa.UniqueConstraint('key', name=op.f('uq__api_keys__key'))
    )
    op.create_table('miner_discoveries',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('uid', sa.Integer(), nullable=False),
    sa.Column('miner_key', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('rank', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk__miner_discoveries')),
    sa.UniqueConstraint('miner_key', name=op.f('uq__miner_discoveries__miner_key'))
    )
    op.create_table('miner_receipts',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('miner_key', sa.String(), nullable=False),
    sa.Column('tweet_id', sa.String(), nullable=False),
    sa.Column('tweet_created_at', sa.DateTime(), nullable=False),
    sa.Column('tweet_user_name', sa.String(), nullable=False),
    sa.Column('tweet_retweet_count', sa.BigInteger(), nullable=False),
    sa.Column('tweet_reply_count', sa.BigInteger(), nullable=False),
    sa.Column('tweet_like_count', sa.BigInteger(), nullable=False),
    sa.Column('tweet_quote_count', sa.BigInteger(), nullable=False),
    sa.Column('tweet_bookmark_count', sa.BigInteger(), nullable=False),
    sa.Column('tweet_impression_count', sa.BigInteger(), nullable=False),
    sa.Column('tweet_content', sa.Text(), nullable=False),
    sa.Column('score', sa.BigInteger(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk__miner_receipts')),
    sa.UniqueConstraint('miner_key', 'tweet_id', name='uq_miner_key_tweet_id'),
    sa.UniqueConstraint('tweet_id', name=op.f('uq__miner_receipts__tweet_id'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('miner_receipts')
    op.drop_table('miner_discoveries')
    op.drop_table('api_keys')
    # ### end Alembic commands ###
