"""add twitt blacklisting

Revision ID: 002
Revises: 001
Create Date: 2024-09-22 16:06:01.119004

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '002'
down_revision: Union[str, None] = '001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('miner_twitter_posts_blacklist',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('tweet_id', sa.String(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk__miner_twitter_posts_blacklist')),
    sa.UniqueConstraint('tweet_id', name='uq_tweet_id'),
    sa.UniqueConstraint('tweet_id', name=op.f('uq__miner_twitter_posts_blacklist__tweet_id'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('miner_twitter_posts_blacklist')
    # ### end Alembic commands ###
