"""extender miner discovery

Revision ID: 003
Revises: 002
Create Date: 2024-09-23 21:26:15.848032

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '003'
down_revision: Union[str, None] = '002'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('miner_discoveries', sa.Column('emission', sa.Float(), nullable=False))
    op.add_column('miner_discoveries', sa.Column('followers', sa.Integer(), nullable=False))
    op.add_column('miner_discoveries', sa.Column('following', sa.Integer(), nullable=False))
    op.add_column('miner_discoveries', sa.Column('tweets', sa.Integer(), nullable=False))
    op.add_column('miner_discoveries', sa.Column('likes', sa.Integer(), nullable=False))
    op.add_column('miner_discoveries', sa.Column('listed', sa.Integer(), nullable=False))
    op.create_unique_constraint(op.f('uq__miner_twitter_posts_blacklist__tweet_id'), 'miner_twitter_posts_blacklist', ['tweet_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq__miner_twitter_posts_blacklist__tweet_id'), 'miner_twitter_posts_blacklist', type_='unique')
    op.drop_column('miner_discoveries', 'listed')
    op.drop_column('miner_discoveries', 'likes')
    op.drop_column('miner_discoveries', 'tweets')
    op.drop_column('miner_discoveries', 'following')
    op.drop_column('miner_discoveries', 'followers')
    op.drop_column('miner_discoveries', 'emission')
    # ### end Alembic commands ###
