"""extended tables

Revision ID: 006
Revises: 005
Create Date: 2024-09-24 09:51:02.465816

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '006'
down_revision: Union[str, None] = '005'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('miner_twitter_posts_blacklist')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('miner_twitter_posts_blacklist',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('tweet_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('timestamp', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('reason', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='pk__miner_twitter_posts_blacklist'),
    sa.UniqueConstraint('tweet_id', name='uq__miner_twitter_posts_blacklist__tweet_id'),
    sa.UniqueConstraint('tweet_id', name='uq_tweet_id')
    )
    # ### end Alembic commands ###
