"""extended tables

Revision ID: 008
Revises: 007
Create Date: 2024-09-24 13:56:17.651460

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '008'
down_revision: Union[str, None] = '007'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('miner_receipts', 'tweet_user_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('miner_receipts', sa.Column('tweet_user_name', sa.VARCHAR(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
