"""extended tables

Revision ID: 010
Revises: 009
Create Date: 2024-10-01 18:20:27.470855

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '010'
down_revision: Union[str, None] = '009'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('miner_receipts', 'score',
               existing_type=sa.BIGINT(),
               type_=sa.Float(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('miner_receipts', 'score',
               existing_type=sa.Float(),
               type_=sa.BIGINT(),
               existing_nullable=False)
    # ### end Alembic commands ###
